config/routes.rb
Homie::Application.routes.draw do
  
  root :to => 'home#index'

  post '/reviews', to: 'reviews#create', as: 'create_review'
  get "reviews/:id/edit", to: 'reviews#edit', as: 'edit_review'
  put "reviews/:id", to: 'reviews#update', as: 'update_review'
  get "reviews/:apt_id", to: 'reviews#find_by_apt', as: 'reviews_find_by_apt'
  delete 'reviews/:id', to: 'reviews#delete', as:'delete_review'

  post '/pictures', to: 'pictures#create', as: 'create_picture'
  delete 'pictures/:id', to: 'pictures#delete', as:'delete_picture'

  get 'apartments/search', to: 'apartments#search'
  resources :apartments do
    member do
      post 'favorite', to: 'apartments#favorite'
    end
  end

  devise_for :users 
  resources :users, :only => [:show]

  
  









end

app/models/apartment.rb
# == Schema Information
#
# Table name: apartments
#
#  id                     :integer          not null, primary key
#  title                  :string(255)
#  description            :text
#  price                  :float
#  bathrooms              :float
#  bedrooms               :float
#  average_overall_rating :float
#  created_at             :datetime
#  updated_at             :datetime
#  user_id                :integer
#  street_address         :string(255)
#  apartment_number       :string(255)
#  city                   :string(255)
#  state                  :string(255)
#  zip                    :integer
#  photo_file_name        :string(255)
#  photo_content_type     :string(255)
#  photo_file_size        :integer
#  photo_updated_at       :datetime
#

class Apartment < ActiveRecord::Base
	has_many :reviews
	has_many :pictures
	belongs_to :user, class_name: 'User', foreign_key: 'user_id'
	has_attached_file :photo, styles: {thumb: "75x75>", small: "500x500>", large: "1200x1200>"}
	#validates_attachment :photo, content_type: { content_type: ["photo/jpg", "photo/jpeg", "photo/png"] }
	do_not_validate_attachment_file_type :photo
	make_flaggable

	validates :user_id, :street_address, :title, :city, :state, :zip, :description, :bedrooms, :bathrooms, presence: true
	#validates :street_address, presence: true, uniqueness: { case_sensitive: false }
	validates :price, presence: true, numericality: { greater_than: 0}

	SUCCESS = 1
  	FORBIDDEN = 403

  	#adds a new apartment to the database and returns errorCode if not valid.
	def self.add(user_id, title, street_address, apartment_number, city, state, zip, description, price, bedrooms, bathrooms)
		if self.where('street_address = ? AND apartment_number = ?', street_address, apartment_number).empty?
			apartment = new(user_id: user_id, title: title, street_address: street_address, apartment_number: apartment_number, city: city, state: state, zip: zip, description: description, price: price, bedrooms: bedrooms, bathrooms:bathrooms)
			apartment.save
			return apartment
		end
		#apartment.errors.messages
		#FORBIDDEN
	end

	#update the description for this apartment record and then returns FORBIDDEN if
	#the updates are not valid; otherwise returns 1 for success
	def update(user_id, title, street_address, apartment_number, city, state, zip, description, price, bedrooms, bathrooms)
		valid = self.update_attributes(user_id: user_id, title: title, street_address: street_address, apartment_number: apartment_number, city: city, state: state, zip: zip, description: description, price: price, bedrooms: bedrooms, bathrooms:bathrooms)
		return self if valid
		FORBIDDEN
	end

	def updateApt(params)
		valid = self.update_attributes(params)
		return self if valid
		FORBIDDEN
	end

  searchable do
    text :title, :street_address, :apartment_number, :city, :state, :zip

    float :price
    float :bathrooms
    float :bedrooms
    float :average_overall_rating
  end

	def delete()
		self.destroy
	end

	#pass in a price, return it in float format
	def self.parsePrice(p)
		p = p.to_s
		p = p.gsub(/[$,_]/,'').to_f
		return p
	end

	def self.favorite(user_id, apt_id)
		user = User.find_by_id(user_id)
		if !user
			return -1
		end
		apt = Apartment.find(apt_id)
		list = user.flagged_apartments
		if user.flagged?(apt)
			#check whether the apt is in list
        	user.unflag(apt)
        	list.delete(apt)
        	return 200
      	else
      		#apt is not in list
        	user.flag(apt, :favorite)
        	return 201
      	end
	end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  include ApartmentsHelper

  SUCCESS = 1
  FORBIDDEN = 403
  PAGE_NOT_FOUND = 404

  # def favorite
  #   if !current_user
  #     redirect_to new_user_session_url, :notice => "You need to Login to add favorite"
  #   else
  #     @current_user = current_user
  #     @apt = Apartment.find(params[:id])
  #     @list = current_user.flagged_apartments
  #     if @current_user.flagged?(@apt)
  #       @current_user.unflag(@apt)
  #       @list.delete(@apt)
  #       redirect_to apartment_path, :notice => "You removed this apartment to your favourite list"
  #     else
  #       @current_user.flag(@apt, :favorite)
  #       redirect_to apartment_path, :notice => "You added this apartment to your favourite list"
  #     end
  #   end
  # end

  def favorite
    @current_user = current_user
    @apt = Apartment.find(params[:id])
    result = Apartment.favorite(@current_user, @apt)
    if result == 200
      render json: {errCode: 200}
    elsif result == 201
      render json: {errCode: 201}
    else
      render json: {errCode: -1}
    end
  end

  #Loads the apartment profile page with reviews. Provides user with option to add reviews
  #if the user is logged in and hasn't already added a review.
  def show
    @apartment = Apartment.find(params[:id])
    @reviews = Review.find_by_apt(params[:id]) 
    @pictures = @apartment.pictures
    @review = Review.new
    @picture = Picture.new
    @reviewed = Review.hasReviewed(current_user, params[:id])
    @loggedIn = current_user
    if current_user
      @user_id = current_user.id
    end
    #boolean value used in view to decide whether user can add new review
    # @show_form = can_review?(@reviews)        #method from ApartmentsHelper
  end

  #Page for creating new apartment profile.
  def new
    @apartment = Apartment.new
    if !current_user
      flash[:error] = "You must be logged in to create new apartment profile"
      redirect_to root_path
    end
  end

  #Creates and saves new apartment profile if information is valid; otherwise reloads page for
  #creating new profiles.
  def create
    user_id = current_user.id
    params[:apartment][:user_id] = user_id
    price = params[:apartment][:price]
    params[:apartment][:price] = Apartment.parsePrice(price)
    street_address = params[:apartment][:street_address]
    apartment_number = params[:apartment][:apartment_number]

=begin
    title = params[:apartment][:title]
    city = params[:apartment][:city]
    state = params[:apartment][:state]
    zip = params[:apartment][:zip]
    desc = params[:apartment][:description]
    price = params[:apartment][:price]
    params[:apartment][:price] = Apartment.parsePrice(price)
    beds = params[:apartment][:bedrooms]
    baths = params[:apartment][:bathrooms]
    street_address = params[:street_address]
    apartment_number = params[:apartment_number]
    @apartment = Apartment.add(user_id, title, street_address, apartment_number, city, state, zip, desc, price, beds, baths)
=end

    @apartment = Apartment.new(apt_params)
    if Apartment.where('street_address = ? AND apartment_number = ?', street_address, apartment_number).empty?    
      if @apartment.save
        redirect_to @apartment
      else
        render "new"
      end
    else
      flash[:error] = "Error: Apartment with same address and apartment number already exists\n"
      redirect_to new_apartment_path
    end
  end

  #Page for editing apartment profile information.
  def edit
    @apartment = Apartment.find_by_id(params[:id])
    if !@apartment
      flash[:error] = "Error: Apartment page not found\n"
      redirect_to root_path
    elsif !current_user
      flash[:error] = "Error: user must be signed in to edit\n"
      redirect_to @apartment
    elsif @apartment.user_id != current_user.id
      flash[:error] = "Error: only the owner is allowed to edit\n"
      redirect_to @apartment
    end
  end

  #Saves updates to apartment profile if changes are valid; otherwise reload edit page.
  def update
    @apartment = Apartment.find(params[:id])
    user_id = current_user.id
    params[:apartment][:user_id] = user_id
    price = params[:apartment][:price]
    params[:apartment][:price] = Apartment.parsePrice(price)

=begin
    title = params[:apartment][:title]
    street_address = params[:apartment][:street_address]
    apartment_number = params[:apartment][:apartment_number]
    city = params[:apartment][:city]
    state = params[:apartment][:state]
    zip = params[:apartment][:zip]
    description = params[:apartment][:description]
    price = params[:apartment][:price]
    params[:apartment][:price] = Apartment.parsePrice(price)
    beds = params[:apartment][:bedrooms]
    baths = params[:apartment][:bathrooms]
    result = @apartment.update(user_id, title, street_address, apartment_number, city, state, zip, description, price, beds, baths)
=end

    if @apartment.update_attributes(apt_params)
      redirect_to @apartment
    else 
      render "edit"
    end
  end

  def with_price(query)
    min_price = params[:min_price]
    max_price = params[:max_price]
    lowest_price = (min_price.presence || 0).to_f
    highest_price = (max_price.presence || Apartment.maximum("price")).to_f
    query.with(:price).between(lowest_price..highest_price)
  end

  def with_rating(query)
    min_rating = params[:min_rating]
    lowest_rating = (min_rating.presence || 0).to_f
    or_nil = (min_rating.presence || nil)
    if min_rating == (min_rating.presence || 0)
      query.with(:average_overall_rating).greater_than_or_equal_to(lowest_rating)
    elsif min_rating == or_nil
      query.with(:average_overall_rating)
    end

  end

  def with_bedrooms(query)
    min_bedrooms = params[:min_bedrooms]
    max_bedrooms = params[:max_bedrooms]
    lowest_bedrooms = (min_bedrooms.presence || 0).to_f
    highest_bedrooms = (max_bedrooms.presence || Apartment.maximum("bedrooms")).to_f
    query.with(:bedrooms).between(lowest_bedrooms..highest_bedrooms)
  end

  def with_bathrooms(query)
    min_bathrooms = params[:min_bathrooms]
    max_bathrooms = params[:max_bathrooms]
    lowest_bathrooms = (min_bathrooms.presence || 0).to_f
    highest_bathrooms = (max_bathrooms.presence || Apartment.maximum("bathrooms")).to_f
    query.with(:bedrooms).between(lowest_bathrooms..highest_bathrooms)
  end

  def low_high_sort(query)
    sort = params[:sorting]
    if sort == "Ratings: low to high"
      query.order_by(:average_overall_rating, :asc)
    elsif sort == "Ratings: high to low"
      query.order_by(:average_overall_rating, :desc)
    elsif sort == "Price: low to high"
      query.order_by(:price, :asc)
    elsif sort == "Price: high to low"
      query.order_by(:price, :desc)
    else # default sort from highest to lowest rating
      query.order_by(:average_overall_rating, :desc)
    end
  end


  #Searches for apartment listings
  def search
    @search = Apartment.search do |query|
      query.fulltext params[:search]
      with_price(query)
      with_rating(query)
      with_bedrooms(query)
      with_bathrooms(query)
      low_high_sort(query)
    end

    @apartments = @search.results
    @max_price = Apartment.maximum("price") || 5000
    @max_bedrooms = Apartment.maximum("bedrooms") || 6
    @max_bathrooms = Apartment.maximum("bathrooms") || 6
  end

  def destroy
    @apartment = Apartment.find_by_id(params[:id])
    #print "destroy apartment"
    if !@apartment
      #p "no apartment"
      flash[:error] = "Error: Apartment page not found\n"
      redirect_to root_path
    elsif !current_user
      #p "not signed in"
      flash[:error] = "Error: user must be signed in to delete apartment\n"
      redirect_to @apartment
    elsif @apartment.user_id != current_user.id
      #p "not owner"
      flash[:error] = "Error: only the owner is allowed to delete apartment\n"
      redirect_to @apartment
    else
      #print "successful"
      @apartment.delete()
      redirect_to root_path
    end
  end

  private
  def apt_params
    params.require(:apartment).permit(:title, :description, :price, :bathrooms, :bedrooms, :user_id, :apartment_number, :street_address, :city, :state, :zip, :price, :photo)
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
  # not using this in iteration one, will add this back for the next iteration

  # def can_review?(apt_reviews)
  #   if current_user
  #     user_reviews = Review.where(:user_id => current_user.id)
  #     past_review = apt_reviews & user_reviews
  #     return true if !past_review
  #   end
  #   return false
  # end
end

app/views/apartments/create.html.erb
<h1>Apartments#create</h1>
<p>Find me in app/views/apartments/create.html.erb</p>

app/views/apartments/delete.html.erb
<h1>Apartments#delete</h1>
<p>Find me in app/views/apartments/delete.html.erb</p>

app/views/apartments/edit.html.erb
<h1>Edit apartment</h1>


<%= form_for(@apartment, html: { multipart: true}) do |f| %>

  <%= render 'shared/error_messages' %> 

  <div><br /><%= f.label :photo, "Upload image" %>
   <%= f.file_field :photo %><br /></div>

  <div><%= f.label :Title %>
  <%= f.text_field :title %><br /></div>

   <div><%= f.label :Street_Address %>
  <%= f.text_field :street_address %><br /></div>

  <div><%= f.label :Apartment_Number %>
    <%= f.text_field :apartment_number %> (optional)<br /></div>

  <div><%= f.label :City %>
    <%= f.text_field :city %><br /></div>

  <div><%= f.label :State %>
    <%= f.text_field :state %><br /></div>

  <div><%= f.label :Zip %>
    <%= f.text_field :zip %><br /></div>

  <div><%= f.label :Description %>
  <%= f.text_area :description %><br /></div>

  <div><%= f.label :price %>
  <%= f.text_field :price %><br /></div>

  <div><%= f.label :bedrooms %>
   <%= f.select :bedrooms, 1..10, :selected => @apartment.bedrooms.to_i %><br /></div>

  <div><%= f.label :bathrooms %>
   <%= f.select :bathrooms, 1..10, :selected => @apartment.bathrooms.to_i %><br /><br /></div>
   
  <div><%= f.submit "Save", :class => 'button small' %></div>
<% end %>

app/views/apartments/new.html.erb
<h1>Create a new apartment</h1>

<%= flash[:error].html_safe unless flash[:error].blank? %>

<%= form_for(@apartment, html: { multipart: true}) do |f| %>

  <%= render 'shared/error_messages' %>

  <div><br /><%= f.label :photo, "Upload image" %>
   <%= f.file_field :photo %><br /><br /></div>

  <div><%= f.label :Title %>
  <%= f.text_field :title %><br /><br /></div>

   <div><%= f.label :Street_Address %>
  <%= f.text_field :street_address %><br /><br /></div>

  <div><%= f.label :Apartment_Number %>
    <%= f.text_field :apartment_number %> (optional)<br /><br /></div>

  <div><%= f.label :City %>
    <%= f.text_field :city %><br /><br /></div>

  <div><%= f.label :State %>
    <%= f.text_field :state %><br /><br /></div>

  <div><%= f.label :Zip %>
    <%= f.text_field :zip %><br /><br /></div>

  <div><%= f.label :Description %>
  <%= f.text_area :description %><br /><br /></div>

  <div><%= f.label :price %>
  <%= f.text_field :price %><br /><br /></div>

  <div><%= f.label :bedrooms %>
   <%= f.select :bedrooms, 1..10 %><br /><br /></div>

  <div><%= f.label :bathrooms %>
   <%= f.select :bathrooms, 1..10 %><br /><br /></div>

  <div><%= f.submit "Create Apartment", :class => 'button small' %></div>
<% end %>

app/views/apartments/search.html.erb
<%= form_tag apartments_search_path, id: "search_form", method: 'get' do %>

  <%= text_field_tag :search, params[:search], id: "search_field", placeholder: "Search address or listing title" %>
  <%= submit_tag "Search", name: nil, class: "button small" %> 
  <%= select_tag "sorting", options_for_select([ "Ratings: high to low", "Ratings: low to high", "Price: high to low", "Price: low to high" ], :selected => params[:sorting]), :onchange => "this.form.submit();" %>
  <div id="filters">
    <span>Filters:</span>

      <%= label_tag :price, "Price"%>
      <%= text_field_tag :min_price, params[:min_price], placeholder: 0 %>
      <span>to</span>
      <%= text_field_tag :max_price, params[:max_price], placeholder: @max_price.round(0) %>

      <%= label_tag :rating, "Minimum Rating"%>
      <%= text_field_tag :min_rating, params[:min_rating], placeholder: 0 %>

      <%= label_tag :bedrooms, "Bedrooms" %>
      <%= text_field_tag :min_bedrooms, params[:min_bedrooms], placeholder: 1 %>
      <span>to</span>
      <%= text_field_tag :max_bedrooms, params[:max_bedrooms], placeholder: @max_bedrooms.round(0) %>

      <%= label_tag :bathrooms, "Bathrooms" %>
      <%= text_field_tag :min_bathrooms, params[:min_bathrooms], placeholder: 1 %>
      <span>to</span>
      <%= text_field_tag :max_bathrooms, params[:max_bathrooms], placeholder: @max_bathrooms.round(0) %>

      <%= link_to "Clear", "#", id: "reset_filters" %>
    </div>
<% end %>

<h2>Search results</h2>
<div id="results">

  <!-- <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4"> -->
  
  <% @apartments.each do |apt| %>

    <div class="search-result">
      <div class="listing-images">
        <div class="listing-images-container">
          <% if apt.photo.exists? %>
            <%= image_tag apt.photo.url(:small) %>
          <% end %>
        </div>
        <div class="listing-price">
          <span class="currency"></span><span class="amount"><%= apt.price.round(0) %></span>
        </div>
        
        <%= link_to "", apt, { class: "target-view" } %>
        
        <div class="listing-favorite">
          <% if current_user %>
            <li class="favo" id="<%= "#{apt.id}" %>" on="true"></li>
            
            <script type="text/javascript">
              $('#<%= "#{apt.id}" %>').click(function() {
                user_id = <%=(current_user)? current_user.id : nil%>;
                apt_id = <%=apt.id%>;
                console.log(apt_id);

                  $.ajax({
                      type: 'POST',
                      url: "/apartments/<%= apt.id %>/favorite",
                      data: JSON.stringify( {user_id: user_id, apartment_id: apt_id} ),
                      contentType: "application/json",
                      dataType: "json",
                      success: handle_favorite(apt_id),
                      error: function(err) { alert('error occurred on request'); }
                  });
              });
              </script>

              <% if current_user.flagged?(Apartment.find(apt.id))  %>
                <script type="text/javascript">
                  $('#<%= "#{apt.id}" %>').removeClass('off-star');
                  document.getElementById('<%= "#{apt.id}" %>').setAttribute("on", "true");
                </script>
              <% else %>
                <script type="text/javascript">
                  $('#<%= "#{apt.id}" %>').addClass('off-star');
                  document.getElementById('<%= "#{apt.id}" %>').setAttribute("on", "false");
                </script>
              <% end %>

          <% else %>
            <%= link_to "", new_user_session_path, { class: "not-favorited" } %>
          <% end %>
        </div>
      </div>
      <div class="listing-footer">
        <div class="listing-title">
          <%= link_to apt.title, apt %>
        </div>
        <div class="listing-address">
          <%= apt.street_address %> <%= apt.apartment_number %> <%= apt.city %> <%= apt.state %> <%= apt.zip %>
        </div>
        <div class="listing-rooms">
          <div class="listing-bedrooms">
            <%= apt.bedrooms.round(0) %> bed
          </div>
          <div class="listing-bathrooms">
            <%= apt.bathrooms.round(0) %> bath
          </div>
        </div>
        <div class="listing-rating">
          <% if !apt.average_overall_rating %>
            <div class="rating-0"></div>
          <% else %>
            <% if number_with_precision(apt.average_overall_rating, precision: 0) == 0 %>
              <div class="rating-1 %>"></div>
            <% end %>
              <div class="rating-<%= number_with_precision(apt.average_overall_rating, precision: 0) %>"></div>
          <% end %>
        </div>
      </div>
    </div>

  <% end %>

</div>

<script type="text/javascript">
var handle_favorite = function(id) {
  var sel = $('#'+id).attr('on');
  if (sel == "true") {
    $('#'+id).addClass('off-star');
    $('#'+id).attr("on", "false");
  } else {
    $('#'+id).removeClass('off-star');
    $('#'+id).attr("on", "true");
  }
}
</script>

app/views/apartments/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?sensor=false&v=3&libraries=geometry,places"></script>

<h1><%= @apartment.title %></h1>

<div id="map"></div>

<% if @user_id == @apartment.user_id %>
	<div class="actions">
		<%= link_to "Edit", edit_apartment_path(id: @apartment.id), :class => 'button small' %>
		<%= link_to "Delete", apartment_path(id: @apartment.id), :class => 'button alert small', :data => { :confirm => "Are you sure?" }, :method => :delete %>
	</div>
<% end %>

<% if current_user %>
	<div class="favorite">
	<li id="favo" on="true"></li>
	<% if current_user.flagged?(Apartment.find(@apartment.id))	%>
		<script type="text/javascript">
			$('#favo').removeClass('off-star');
			document.getElementById('favo').setAttribute("on", "true");
		</script>
	<% else %>
		<script type="text/javascript">
			$('#favo').addClass('off-star');
			document.getElementById('favo').setAttribute("on", "false");
		</script>
	<% end %>
	</div>
<% end %>

<% if @apartment.photo.exists? || @pictures.size > 0 %>
	<div class="photos">
		<div class="fotorama" data-nav="thumbs" data-fit="cover" data-keyboard="true" data-allowfullscreen="true" data-width="600px" data-ratio="800/500">
			<% if @apartment.photo.exists? %>
				<%= image_tag @apartment.photo.url(:large) %>
			<% end %>
			<% if @pictures.size > 0 %>
		  		<% @pictures.each do |picture| %>
		  			<% if !picture.image_file_name.nil? %>
						<%= image_tag picture.image.url(:large) %>
					<% end %>
				<% end %>
			<% end %>
		</div>
	</div>
<% end %>

<h4 id='apt-street'>
	<%= @apartment.street_address %> 
	<%= @apartment.apartment_number %>
	<%= @apartment.city %>
	<%= @apartment.state %> 
	<span id="apt-zip"><%= @apartment.zip %></span>
</h4>

<div class="rating-info">
	<div class="rating">
	  <% if !@apartment.average_overall_rating %>
	    <div class="rating-0"></div>
	  <% else %>
	    <% if number_with_precision(@apartment.average_overall_rating, precision: 0) == 0 %>
	      <div class="rating-1 %>"></div>
	    <% else %>
	      <div class="rating-<%= number_with_precision(@apartment.average_overall_rating, precision: 0) %>"></div>
	    <% end %>
	  <% end %>
	</div>
	<% if @reviews.size == 1 %>
		<div class="rating-count">1 rating</div>
	<% else %>
		<div class="rating-count"><%= @reviews.size %> ratings</div>
	<% end %>
</div>


<div class="price"><%= number_to_currency(@apartment.price, unit: "$") %></div>

<div class="details">
	<div class="bedrooms"><%= @apartment.bedrooms.round(0) %> bedrooms</div>
	<div class="bathrooms"><%= @apartment.bathrooms.round(0) %> bathrooms</div>
	<div class="description"><%= @apartment.description %></div>
</div>

<br />
<% if @loggedIn %>
	<h2>Share Photo</h2>

	<%= form_for(@picture, :url => create_picture_path, :html => { method: "post", multipart: true }) do |f| %>
	  <p>Do you live here? Share your photo of the place.</p>
	  <%= f.file_field :image, required: true %>
	  <%= f.hidden_field :apartment_id, value: @apartment.id %>
	  <input class="button tiny" name="commit" type="submit" value="Upload">
	<% end %>
<% end %>

<br />

<% if !@reviewed && @loggedIn %>
	<h2>Create Review</h2>

	<%= form_for @review, url: "/reviews", html: {method: :post} do |f| %>

		<div><%= f.label :Overall_Rating %>
		<ul class="rating">
			<% (1..5).each do |i| %>
				<li class="rating_star" data-apt-id="<%= @apartment.id %>" data-stars="<%= i %>" id="<%= "#{@apartment.id}_#{i}" %>"></li>
			<% end %>
		</ul>
		<br />
		<br />
		<br />
		<%= f.select :overall_rating, 1..5 %></div>

		<div><%= f.label :Review %><br />
		<%= f.text_area :review, size: "60x12", placeholder: "What do you think of this place?" %><br /><br /></div>

		<%= f.hidden_field :apartment_id, value: @apartment.id %>

		<div><%= f.submit "Submit", class: "button small" %><br /><br /></div>
	<% end %>
<% end %>

<% if !@reviews.blank? %>
<h2>Reviews</h2>
<% end %>

<div class="reviews">

<% @reviews.each do |review| %>
	<div class="review">
		<div class="reviewer">
			<div class="reviewer-image">
			<% if review.user.photo.exists? %>
				<%= image_tag review.user.photo.url(:small) %>
			<% end %>
			</div>
		</div>
		<div class="callout">
			<div class="rating">
				<div class="rating-<%= number_with_precision(review.overall_rating, precision: 0) %>"></div>
			</div>

			<% if review.review != nil %>
			    <div class="review-description"><%= review.review %></div>
			<% end %>

			<div class="reviewer-name">
				<%= link_to review.user.username, user_path(id: review.user_id) %>
			</div>
			<div class="review-updated">
				Updated <%= review.user.updated_at.to_formatted_s(:long)  %>
			</div>
			<% if review.user_id == @user_id.to_i %>
				<div class="actions">
					<%= link_to "Edit" , edit_review_path(id: review.id), :class => 'button tiny' %>
					<%= link_to "Delete", delete_review_path(id: review.id), :class => 'button alert tiny', :data => { :confirm => "Are you sure?" }, :method => :delete %>
				</div>
		<% end %>
		</div>
	</div>
<% end %>
</div>



<script type="text/javascript">
$('#corresponed_user').hide();

function handle_favorite() {
	var sel = document.getElementById('favo').getAttribute('on');
	if (sel == "true") {
		$('#favo').addClass('off-star');
		document.getElementById('favo').setAttribute("on", "false");
	} else {
		$('#favo').removeClass('off-star');
		document.getElementById('favo').setAttribute("on", "true");
	}
}

$('#favo').click(function() {
	user_id = <%=(current_user)? current_user.id : nil%>
    apt_id = <%=@apartment.id%>

    $.ajax({
        type: 'POST',
        url: "/apartments/<%= @apartment.id %>/favorite",
        data: JSON.stringify( {user_id: user_id, apartment_id: apt_id} ),
        contentType: "application/json",
        dataType: "json",
        success: handle_favorite(),
        error: function(err) { alert('error occurred on request'); }
    });
});
</script>

app/views/apartments/update.html.erb
<h1>Apartments#update</h1>
<p>Find me in app/views/apartments/update.html.erb</p>