config/routes.rb
Homie::Application.routes.draw do
  
  root :to => 'home#index'

  post '/reviews', to: 'reviews#create', as: 'create_review'
  get "reviews/:id/edit", to: 'reviews#edit', as: 'edit_review'
  put "reviews/:id", to: 'reviews#update', as: 'update_review'
  get "reviews/:apt_id", to: 'reviews#find_by_apt', as: 'reviews_find_by_apt'
  delete 'reviews/:id', to: 'reviews#delete', as:'delete_review'

  post '/pictures', to: 'pictures#create', as: 'create_picture'
  delete 'pictures/:id', to: 'pictures#delete', as:'delete_picture'

  get 'apartments/search', to: 'apartments#search'
  resources :apartments do
    member do
      post 'favorite', to: 'apartments#favorite'
    end
  end

  devise_for :users 
  resources :users, :only => [:show]

  
  









end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homie</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.css" rel="stylesheet"> 
  <script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.js"></script>
  <%= csrf_meta_tags %>
</head>

<% if current_page?(root_url) %>
<body class="home">
<% else %>
<body>
<% end %>

<% if current_user %>
  <div class="nav">
    <%= link_to "", root_path, class: "logo" %>
    
    <% if !current_page?(root_url) && !current_page?(apartments_search_url) %>
      <%= form_tag apartments_search_path, :class => 'search', :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :id => 'search_field', :placeholder => "Search address or listing title" %>
        <%= submit_tag "Search", name: nil, class: "button small" %> 
      <% end %> 
    <% end %>

    <div class="links">
      <%= link_to "Add apartment", new_apartment_path %>
      <%= link_to "Edit profile", edit_user_registration_path %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    </div>
  </div>
<% else %>
  <div class="nav">
    <%= link_to "", root_path, class: "logo" %>
    <div class="links">
      <%= link_to "Sign Up", new_user_registration_url %>
      <%= link_to "Log In", new_user_session_url %>
    </div>
  </div>
<% end %>

<div class="main">
  <div class="notice"><%= notice %></div>
  <div class="alert"><%= alert %></div>
  <%= yield %>
</div>

</body>
</html>